name: european_countries
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  dio: ^5.6.0
  retrofit: ^4.2.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  retrofit_generator: ^8.2.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter:

  uses-material-design: true

 
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  